"""Defined dtypes for the dataframe based on https://github.com/MyScrapers/Alpinescraper/blob/master/src/Alpinescraper/common/items.py."""

dtypes = {
    "DATE": "string",
    "PRICE": "float",
    "REFERENCE": "string",
    "SPIDER": "string",
    "TITLE": "string",
    "URL": "string",
    "AGENCY": "string",
    "COOWNERSHIP": "string",
    "BALCONY_COUNT": "Int64",  # Use pandas nullable integer type
    "BATHROOMS": "float",
    "WC": "float",
    "BEDROOMS": "float",
    "CURRENCY": "string",
    "DESCRIPTION": "string",
    "ELEVATOR": "boolean",
    "ENERGY_PERFORMANCE": "string",
    "EXTERNAL_SIZE": "float",
    "EXTERIOR_AMENITIES": "string",
    "FLOOR": "Int64",
    "GARAGE": "Int64",
    "GARDEN": "string",
    "GREENHOUSE_EMISSION": "string",
    "HEATING": "string",
    "INTERIOR_AMENITIES": "string",
    "KITCHEN_TYPE": "string",
    "LOCATION": "string",
    "NB_FLOOR": "Int64",
    "PARKING": "Int64",
    "POOL": "Int64",
    "ROOMS": "float",
    "SIZE": "float",
    "STATUS": "string",
    "TERRACE": "boolean",
    "TYPE": "string",
    "VIEW": "string",
    "YEAR_OF_CONSTRUCTION": "Int64",
}
